### ISSUE TITLE
Angular4 deprecates OpaqueToken

### ISSUE THREAD

**Issue by xwipeoutx** [tristanmenzel/ng2-loading-pane#2]
See https://github.com/angular/angular/issues/14763

The advice is to use `InjectionToken<string>` instead

This manifests with the following error:

```
ERROR in node_modules/ng2-loading-pane/dist/services/work-tracker.service.d.ts(1,10): error TS2305: Module '"C:/code/sandbox/test-ng2-loading/test-the-thing/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

This is with an app created as such:
```
> ng new test-the-thing
> yarn add ng2-loading-pane
(Update app.module.ts to include the loading pane)
> ng serve
```

**Comment by tristanmenzel** [comment]
This has been resolved in the latest version where we do away with the factory service all together.
